language: python

install:
  - pip install codecov
  - pip install coverage

# Run the unit test
script:
  - coverage run test_shuffle.py

# Push the results back to codecov
after_success:
  - codecov
