language: python

install:
  - pip install codecov
  - pip install coverage

script:
  - pytest test_shuffle.py
  - coverage report

# Push the results back to codecov
after_success:
  - bash <(curl -s https://codecov.io/bash) -Z -X gcov -X coveragepy -X search -X xcode -X gcovout -X fix
