language: python

install:
  - pip install codecov
  - pip install coverage


# Push the results back to codecov
after_success:
  - coverage xml
  - coverage report
  - bash <(curl -s https://codecov.io/bash) -Z -X gcov -X coveragepy -X search -X xcode -X gcovout -X fix -f coverage.xml
